version: "2"
linters:
  settings:
    errcheck:
      disable-default-exclusions: false
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*github.com/jpoirier/gortlsdr.Context).CancelAsync
        - (*io.PipeWriter).Close
